import { ResourceItem, ImageStreamResource, HelmReleaseItem, KubeContext, ProjectInfo } from '../types/k8s.js';
import { SemverSorter } from './semver-sorter.js';

export const MOCK_CONTEXTS: KubeContext[] = [
  {
    name: 'devops/api-devops-bt-wan:6443/alexandru.chiscari@btrl.ro',
    cluster: 'api-devops-bt-wan:6443',
    user: 'alexandru.chiscari@btrl.ro',
    namespace: 'devops',
    isCurrent: true,
  },
  {
    name: 'default/api-dev-ocp-bt-wan:6443/alexandru.chiscari@btrl.ro',
    cluster: 'api-dev-ocp-bt-wan:6443',
    user: 'alexandru.chiscari@btrl.ro',
    namespace: 'default',
    isCurrent: false,
  },
  {
    name: 'prod/api-prod-bt-wan:6443/alexandru.chiscari@btrl.ro',
    cluster: 'api-prod-bt-wan:6443',
    user: 'alexandru.chiscari@btrl.ro',
    namespace: 'production',
    isCurrent: false,
  },
];

export const MOCK_PROJECTS: ProjectInfo[] = [
  { name: 'devops', displayName: 'DevOps & CI/CD Platform', status: 'Active', isCurrent: true },
  { name: 'openshift-image-registry', displayName: 'Internal Registry', status: 'Active', isCurrent: false },
  { name: 'production', displayName: 'Production Workloads', status: 'Active', isCurrent: false },
  { name: 'staging', displayName: 'Staging Environment', status: 'Active', isCurrent: false },
  { name: 'default', displayName: 'Default Project', status: 'Active', isCurrent: false },
];

export const MOCK_PODS: ResourceItem[] = [
  {
    id: 'devops/auth-service-789f5c4db-x92kl',
    name: 'auth-service-789f5c4db-x92kl',
    namespace: 'devops',
    kind: 'pods',
    status: 'Running',
    statusColor: 'green',
    ready: '1/1',
    restarts: 0,
    ip: '10.128.2.45',
    node: 'worker-node-01.bt-wan',
    age: '4d',
    labels: { app: 'auth-service', env: 'production', version: 'v2.4.1' },
    raw: { spec: { containers: [{ name: 'auth-container' }] } },
  },
  {
    id: 'devops/payment-gateway-649f8cd79-km82q',
    name: 'payment-gateway-649f8cd79-km82q',
    namespace: 'devops',
    kind: 'pods',
    status: 'Running',
    statusColor: 'green',
    ready: '2/2',
    restarts: 1,
    ip: '10.128.3.112',
    node: 'worker-node-02.bt-wan',
    age: '12d',
    labels: { app: 'payment-gateway', env: 'production' },
    raw: { spec: { containers: [{ name: 'gateway' }, { name: 'envoy-proxy' }] } },
  },
  {
    id: 'devops/frontend-portal-58dc4878cb-8k21m',
    name: 'frontend-portal-58dc4878cb-8k21m',
    namespace: 'devops',
    kind: 'pods',
    status: 'Running',
    statusColor: 'green',
    ready: '1/1',
    restarts: 0,
    ip: '10.128.4.89',
    node: 'worker-node-03.bt-wan',
    age: '2h',
    labels: { app: 'frontend-portal', tier: 'frontend' },
    raw: { spec: { containers: [{ name: 'nginx-portal' }] } },
  },
  {
    id: 'devops/billing-cronjob-28491024-k98sq',
    name: 'billing-cronjob-28491024-k98sq',
    namespace: 'devops',
    kind: 'pods',
    status: 'Completed',
    statusColor: 'blue',
    ready: '0/1',
    restarts: 0,
    ip: '10.128.2.99',
    node: 'worker-node-01.bt-wan',
    age: '1h',
    labels: { job: 'billing-sync' },
    raw: { spec: { containers: [{ name: 'sync-worker' }] } },
  },
  {
    id: 'devops/notification-worker-59b48c9df-v7z8x',
    name: 'notification-worker-59b48c9df-v7z8x',
    namespace: 'devops',
    kind: 'pods',
    status: 'CrashLoopBackOff',
    statusColor: 'red',
    ready: '0/1',
    restarts: 14,
    ip: '10.128.5.21',
    node: 'worker-node-02.bt-wan',
    age: '45m',
    labels: { app: 'notification-worker' },
    raw: { spec: { containers: [{ name: 'worker' }] } },
  },
];

export const MOCK_DEPLOYMENTS: ResourceItem[] = [
  {
    id: 'devops/auth-service',
    name: 'auth-service',
    namespace: 'devops',
    kind: 'deployments',
    status: 'Running',
    statusColor: 'green',
    ready: '3/3',
    age: '45d',
    extra: { desired: 3, current: 3, upToDate: 3, available: 3 },
    labels: { app: 'auth-service' },
  },
  {
    id: 'devops/payment-gateway',
    name: 'payment-gateway',
    namespace: 'devops',
    kind: 'deployments',
    status: 'Running',
    statusColor: 'green',
    ready: '2/2',
    age: '30d',
    extra: { desired: 2, current: 2, upToDate: 2, available: 2 },
    labels: { app: 'payment-gateway' },
  },
  {
    id: 'devops/frontend-portal',
    name: 'frontend-portal',
    namespace: 'devops',
    kind: 'deployments',
    status: 'Running',
    statusColor: 'green',
    ready: '4/4',
    age: '90d',
    extra: { desired: 4, current: 4, upToDate: 4, available: 4 },
    labels: { app: 'frontend-portal' },
  },
  {
    id: 'devops/notification-worker',
    name: 'notification-worker',
    namespace: 'devops',
    kind: 'deployments',
    status: 'Degraded',
    statusColor: 'yellow',
    ready: '0/2',
    age: '12d',
    extra: { desired: 2, current: 2, upToDate: 2, available: 0 },
    labels: { app: 'notification-worker' },
  },
];

export const MOCK_ROUTES: ResourceItem[] = [
  {
    id: 'devops/frontend-portal',
    name: 'frontend-portal',
    namespace: 'devops',
    kind: 'routes',
    status: 'Admitted',
    statusColor: 'green',
    age: '90d',
    extra: {
      host: 'portal.apps.ocp.company.com',
      path: '/',
      targetService: 'frontend-portal',
      tls: 'Edge',
    },
  },
  {
    id: 'devops/api-gateway',
    name: 'api-gateway',
    namespace: 'devops',
    kind: 'routes',
    status: 'Admitted',
    statusColor: 'green',
    age: '60d',
    extra: {
      host: 'api.apps.ocp.company.com',
      path: '/v1',
      targetService: 'payment-gateway',
      tls: 'Passthrough',
    },
  },
];

export const MOCK_SERVICES: ResourceItem[] = [
  {
    id: 'devops/auth-service',
    name: 'auth-service',
    namespace: 'devops',
    kind: 'services',
    status: 'ClusterIP',
    statusColor: 'cyan',
    ip: '172.30.45.12',
    age: '45d',
    extra: { ports: '8080/TCP, 9090/TCP' },
  },
  {
    id: 'devops/payment-gateway',
    name: 'payment-gateway',
    namespace: 'devops',
    kind: 'services',
    status: 'ClusterIP',
    statusColor: 'cyan',
    ip: '172.30.98.54',
    age: '30d',
    extra: { ports: '443/TCP, 80/TCP' },
  },
];

// Rich ImageStreams with multiple SemVer versions for testing the cleanup wizard!
const authServiceTags = SemverSorter.sortTags([
  { tag: 'v2.4.1', created: '2026-08-20T10:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/auth-service@sha256:7f12a...' },
  { tag: 'v2.4.0', created: '2026-08-10T10:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/auth-service@sha256:6e11b...' },
  { tag: 'v2.3.9', created: '2026-07-25T10:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/auth-service@sha256:5d10c...' },
  { tag: 'v2.3.8', created: '2026-07-10T10:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/auth-service@sha256:4c09d...' },
  { tag: 'v2.2.0', created: '2026-06-01T10:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/auth-service@sha256:3b08e...' },
  { tag: 'v1.9.5', created: '2026-04-15T10:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/auth-service@sha256:2a07f...' },
  { tag: 'latest', created: '2026-08-20T10:05:00Z', isSemver: false, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/auth-service@sha256:7f12a...' },
  { tag: 'dev-build-982', created: '2026-08-18T12:00:00Z', isSemver: false, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/auth-service@sha256:1a06a...' },
]);

const frontendPortalTags = SemverSorter.sortTags([
  { tag: 'v3.1.0', created: '2026-08-22T08:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/frontend-portal@sha256:9a...' },
  { tag: 'v3.0.4', created: '2026-08-05T08:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/frontend-portal@sha256:8b...' },
  { tag: 'v3.0.0', created: '2026-07-01T08:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/frontend-portal@sha256:7c...' },
  { tag: 'v2.9.1', created: '2026-05-10T08:00:00Z', isSemver: true, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/frontend-portal@sha256:6d...' },
  { tag: 'latest', created: '2026-08-22T08:05:00Z', isSemver: false, dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/devops/frontend-portal@sha256:9a...' },
]);

export const MOCK_IMAGESTREAMS: ImageStreamResource[] = [
  {
    id: 'devops/auth-service',
    name: 'auth-service',
    namespace: 'devops',
    kind: 'imagestreams',
    status: `${authServiceTags.length} tags`,
    statusColor: 'green',
    age: '120d',
    tags: authServiceTags,
    tagCount: authServiceTags.length,
    extra: {
      tags: authServiceTags,
      tagCount: authServiceTags.length,
      dockerImageRepository: 'image-registry.openshift-image-registry.svc:5000/devops/auth-service',
    },
  },
  {
    id: 'devops/frontend-portal',
    name: 'frontend-portal',
    namespace: 'devops',
    kind: 'imagestreams',
    status: `${frontendPortalTags.length} tags`,
    statusColor: 'green',
    age: '90d',
    tags: frontendPortalTags,
    tagCount: frontendPortalTags.length,
    extra: {
      tags: frontendPortalTags,
      tagCount: frontendPortalTags.length,
      dockerImageRepository: 'image-registry.openshift-image-registry.svc:5000/devops/frontend-portal',
    },
  },
];

export const MOCK_HELM: ResourceItem[] = [
  {
    id: 'devops/ingress-nginx',
    name: 'ingress-nginx',
    namespace: 'devops',
    kind: 'helm',
    status: 'deployed',
    statusColor: 'green',
    age: '45d',
    extra: {
      revision: '4',
      chart: 'ingress-nginx-4.11.2',
      appVersion: 'v1.11.2',
      updated: '2026-08-10 14:22:15.123456 +0300 EEST',
    },
  },
  {
    id: 'devops/redis-cluster',
    name: 'redis-cluster',
    namespace: 'devops',
    kind: 'helm',
    status: 'deployed',
    statusColor: 'green',
    age: '60d',
    extra: {
      revision: '2',
      chart: 'redis-19.5.1',
      appVersion: '7.2.5',
      updated: '2026-07-28 09:15:00.000000 +0300 EEST',
    },
  },
];

export const MOCK_NODES: ResourceItem[] = [
  {
    id: 'master-01.bt-wan',
    name: 'master-01.bt-wan',
    namespace: '',
    kind: 'nodes',
    status: 'Ready',
    statusColor: 'green',
    age: '180d',
    extra: { roles: 'master, control-plane', version: 'v1.30.3' },
  },
  {
    id: 'worker-node-01.bt-wan',
    name: 'worker-node-01.bt-wan',
    namespace: '',
    kind: 'nodes',
    status: 'Ready',
    statusColor: 'green',
    age: '180d',
    extra: { roles: 'worker', version: 'v1.30.3' },
  },
  {
    id: 'worker-node-02.bt-wan',
    name: 'worker-node-02.bt-wan',
    namespace: '',
    kind: 'nodes',
    status: 'Ready',
    statusColor: 'green',
    age: '180d',
    extra: { roles: 'worker', version: 'v1.30.3' },
  },
];
